module.exports.descriptors = [
    `Pretty`,
    `Nice`,
    `Happy`,
    `Roaring`,
    `Friendly`,
    `Cute`,
    `Sweet`,
    `Kitty`,
    `Elephant`,
    `Sugary`,
    `Strong`,
    `Always`,
    `My`,
    `Ocean`,
    `Garden`,
    `Sky`,
    `Dusty`,
    `Cake`,
];

module.exports.places = [`Cafe`, `Coffee`, `Diner`, `Restaurant`, `Bistro`, `Corner`];

// for populating image url and filename
module.exports.images = [
    `https://res.cloudinary.com/hisam/image/upload/v1623175202/cute-spot/zhanjiang-chen-Wg4QjbPLpoM-unsplash_l11bcu.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175202/cute-spot/tony-lee-8IKf54pc3qk-unsplash_gf6eun.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175200/cute-spot/timothy-barlin-GX4YM64o49U-unsplash_artxus.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175200/cute-spot/timothy-barlin-GX4YM64o49U-unsplash_artxus.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175198/cute-spot/timothy-barlin-GX4YM64o49U-unsplash_1_iq3ix1.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175196/cute-spot/y-cai-ZHJLe2y6PMQ-unsplash_jv8zmk.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175193/cute-spot/y-cai-pxMDVnAyh18-unsplash_ohdehe.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175191/cute-spot/rodeo-project-management-software-PYqzYhTNjho-unsplash_vf3vji.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175191/cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_1_rphkkn.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175191/cute-spot/tabitha-turner-k48c--P5MnQ-unsplash_bdakea.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175191/cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_1_rphkkn.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175191/cute-spot/tabitha-turner-k48c--P5MnQ-unsplash_bdakea.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175189/cute-spot/nathan-dumlao-VUR5Yv8eQkU-unsplash_ofdn5z.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175189/cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_welnbh.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175190/cute-spot/seongmi-hong-74DBZldn6xQ-unsplash_opb7ex.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175188/cute-spot/roman-kraft-P8zDQz8Y2Vc-unsplash_z6p1qa.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175185/cute-spot/fabio-alves-djAM7oRJ58M-unsplash_noxdyl.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175183/cute-spot/hardik-pandya-9sz0RKcPAQw-unsplash_qx8coi.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175183/cute-spot/mylene-larnaud-p7w1Uzgqtwg-unsplash_m06cvq.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175182/cute-spot/florencia-viadana-0y92si4ZLyA-unsplash_d56wtq.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175177/cute-spot/daan-evers-tKN1WXrzQ3s-unsplash_s83nqd.jpg`,
    `https://res.cloudinary.com/hisam/image/upload/v1623175178/cute-spot/glen-jackson-xw6OAMF0oQs-unsplash_aanamj.jpg`,
];
// module.exports.fileNames = [
//     `cute-spot/zhanjiang-chen-Wg4QjbPLpoM-unsplash_l11bcu.jpg`,
//     `cute-spot/tony-lee-8IKf54pc3qk-unsplash_gf6eun.jpg`,
//     `cute-spot/timothy-barlin-GX4YM64o49U-unsplash_artxus.jpg`,
//     `cute-spot/timothy-barlin-GX4YM64o49U-unsplash_artxus.jpg`,
//     `cute-spot/timothy-barlin-GX4YM64o49U-unsplash_1_iq3ix1.jpg`,
//     `cute-spot/y-cai-ZHJLe2y6PMQ-unsplash_jv8zmk.jpg`,
//     `cute-spot/y-cai-pxMDVnAyh18-unsplash_ohdehe.jpg`,
//     `cute-spot/rodeo-project-management-software-PYqzYhTNjho-unsplash_vf3vji.jpg`,
//     `cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_1_rphkkn.jpg`,
//     `cute-spot/tabitha-turner-k48c--P5MnQ-unsplash_bdakea.jpg`,
//     `cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_1_rphkkn.jpg`,
//     `cute-spot/tabitha-turner-k48c--P5MnQ-unsplash_bdakea.jpg`,
//     `cute-spot/nathan-dumlao-VUR5Yv8eQkU-unsplash_ofdn5z.jpg`,
//     `cute-spot/nathan-shurr-9-RqJRYnUhU-unsplash_welnbh.jpg`,
//     `cute-spot/seongmi-hong-74DBZldn6xQ-unsplash_opb7ex.jpg`,
//     `cute-spot/roman-kraft-P8zDQz8Y2Vc-unsplash_z6p1qa.jpg`,
//     `cute-spot/fabio-alves-djAM7oRJ58M-unsplash_noxdyl.jpg`,
//     `cute-spot/hardik-pandya-9sz0RKcPAQw-unsplash_qx8coi.jpg`,
//     `cute-spot/mylene-larnaud-p7w1Uzgqtwg-unsplash_m06cvq.jpg`,
//     `cute-spot/florencia-viadana-0y92si4ZLyA-unsplash_d56wtq.jpg`,
//     `cute-spot/daan-evers-tKN1WXrzQ3s-unsplash_s83nqd.jpg`,
//     `cute-spot/glen-jackson-xw6OAMF0oQs-unsplash_aanamj.jpg`,
// ];
